version: "3.7"
services:
  app:
    build:
      args:
        user: ghaith
        uid: 1000
      context: ./
      dockerfile: docker-compose/docker_files/BackendDockerfile
    image: tech-test-app
    depends_on:
      - db
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - laravel

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tech_test_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: db_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge